# appspec.yml

version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ec2-user/app/zip
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  BeforeInstall:
    - location: scripts/beforeInstall.sh
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 360