version: "3"

services:
  web-server:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/service-url.inc:/etc/nginx/conf.d/service-url.inc
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  blue:
    build: .
    image: blue
    container_name: blue
    ports:
      - "8081:8080"
    volumes:
      - ./:/home/ubuntu
      - /etc/localtime:/etc/localtime
    environment:
      active: blue

  green:
    build: .
    image: green
    container_name: green
    ports:
      - "8082:8080"
    volumes:
      - ./:/home/ubuntu
      - /etc/localtime:/etc/localtime
    environment:
      active: blue